### PR TITLE
automatically escape file path's if necessary

### PR DESCRIPTION
**Pull request by Konfekt**

### CODE REVIEW

**Comment by Konfekt** [comment]
Somehow this command is not triggered by a `BufWrite` trigger.

**Comment by chrisbra** [comment]
Why do you need this?

**Comment by Konfekt** [comment]
Because every line `Attach: file with unescaped space in path` is removed and the file not attached.

**Comment by Konfekt** [comment]
If the question referred to the BufWrite trigger, it is a saner alternative to the BufWriteCmd trigger, see https://github.com/chrisbra/CheckAttach/issues/22#issuecomment-398942661 .

Indeed, the `BufWrite` event does not work because `CheckAttach` uses a `BufWriteCmd` trigger.

**Comment by chrisbra** [comment]
I don't understand. For me, it always escapes spaces. And that is what it actually should:

Here for the automatic check on saving:
https://github.com/chrisbra/CheckAttach/blob/b583efd45e03902438a55299623390a0f9253513/ftplugin/mail/CheckAttach.vim#L180-L181

Here when using an external file browser:
https://github.com/chrisbra/CheckAttach/blob/b583efd45e03902438a55299623390a0f9253513/ftplugin/mail/CheckAttach.vim#L211-L212

Here when using `:AttachFile`:
https://github.com/chrisbra/CheckAttach/blob/b583efd45e03902438a55299623390a0f9253513/ftplugin/mail/CheckAttach.vim#L269

So when do you exactly see that problem?

**Comment by Konfekt** [comment]
Yes, CheckAttach  escapes spaces when a file is appended by the `:AttachFile` command, but not when entered directly. That is, for example, after starting a new line with `Attach:` and copy-pasting the file name obtained elsewhere.

**Comment by Konfekt** [comment]
Well, regarding

https://github.com/chrisbra/CheckAttach/blob/b583efd45e03902438a55299623390a0f9253513/ftplugin/mail/CheckAttach.vim#L180-L181

I am lost, it didn't escape spaces over here.

**Comment by Konfekt** [comment]
Well, perhaps use `fnameescape()` instead of `escape(fnamemodify())` ?

**Comment by chrisbra** [comment]
I think the script has been created, when `fnameescape()` wasn't even available yet. BTW: while you can of course manually adding the `:Attach` header, i would not recommend it, because this depends on your `$PWD` and you would need to manually escape strings as you found out.

Regarding:
> I am lost, it didn't escape spaces over here.

Can you step through the function and check why it doesn't work for you? You can manually start debugging by running `:debug :w` and then follow the instructions at `:h debug-scripts`.

**Comment by Konfekt** [comment]
> you would need to manually escape strings as you found out.

There was a misunderstanding. I thought 

https://github.com/chrisbra/CheckAttach/blob/b583efd45e03902438a55299623390a0f9253513/ftplugin/mail/CheckAttach.vim#L180-L181

is there to automatize the escaping when saving or quitting Vim. But it seems to me that
```vim
 let ans = input(prompt, "", "file")
    while (ans != '') && (ans != 'n')
      if empty(s:external_file_browser)
let list = split(expand(ans), "\n")
```
only escapes file names attached by the `CheckAttach` input dialogue. This pull request is about escaping all files that were attached, regardless if by the `CheckAttach` input dialogue or other means (in my case, copy pasting the full path (not using the $PWD)).

**Comment by chrisbra** [comment]
so you are manually adding the pseudo attach header and want the plugin to escape the filename automatically on save?

**Comment by Konfekt** [comment]
That's it, I think. I frequently paste file paths from a file manager, such as Krusader. If these aren't escaped, they disappear on entering the send dialog of mutt.

**Comment by chrisbra** [comment]
Please check current head. I made some changes to your patch and implemented it slightly different. The result should work however. Note, I intentionally did not use `fnameescape()` because I think it might escape too much. Also I wasn't sure, what the `system("test -r"` call was there for in the first place. So I omitted that. It seems to be superfluous and too expansive anyhow.

**Comment by Konfekt** [comment]
>  I wasn't sure, what the system("test -r" call was there for

This checks if the file path is already escaped or not. If the system already recognizes the file, then it must not be escaped. 

> I intentionally did not use fnameescape() because I think it might escape too much
I am not sure why `fnameescape()` should escape too much?

**Comment by chrisbra** [comment]
> I am not sure why fnameescape() should escape too much?

It escapes things such as '%' or '#' for use by e.g. internal Vim commands, that would otherwise expand e.g. '%' to the currently edited file. However, I think those shouldn't be escaped, or else mutt won't find it.

**Pull request closed without merging**
